# NLP Intro

In [9]:
import numpy as np

review1 = "I LOVE this book about love"
review2 = "No this book was okay"

all_words = [text.lower().split() for text in [review1, review2]]
print(all_words)

# flatten this list, can also add lists with + operator
all_words = [word for text in all_words for word in text]
print(f"Flattened all words {all_words}")

unique_words = set(all_words)
print(f"Unique words {unique_words}")

[['i', 'love', 'this', 'book', 'about', 'love'], ['no', 'this', 'book', 'was', 'okay']]
Flattened all words ['i', 'love', 'this', 'book', 'about', 'love', 'no', 'this', 'book', 'was', 'okay']
Unique words {'okay', 'this', 'i', 'was', 'book', 'about', 'love', 'no'}


In [22]:
# make dictionary of all words
vocabulary = {word: index for index, word in enumerate(unique_words)}
print(vocabulary)



def term_frequency_vectorizer(document, vocabulary):
    term_frequency = np.zeros(len(vocabulary))

    for word in document.lower().split():
        index = vocabulary[word]
        term_frequency[index] += 1

    return term_frequency

review1_term_freq = term_frequency_vectorizer(review1, vocabulary)
review2_term_freq = term_frequency_vectorizer(review2, vocabulary)

print(review1)
print(review1_term_freq)
print(review2_term_freq)

{'okay': 0, 'this': 1, 'i': 2, 'was': 3, 'book': 4, 'about': 5, 'love': 6, 'no': 7}
I LOVE this book about love
[0. 1. 1. 0. 1. 1. 2. 0.]
[1. 1. 0. 1. 1. 0. 0. 1.]


In [26]:
import pandas as pd

bag_of_words = pd.DataFrame([review1_term_freq, review2_term_freq], columns=vocabulary.keys(), dtype="int16")

bag_of_words

okay  this  i  was  book  about  love  no
0     0     1  1    0     1      1     2   0
1     1     1  0    1     1      0     0   1

## Feature extraction with sklearn

In [45]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, TfidfVectorizer

count_vectorizer = CountVectorizer()
bag_of_words_sparse = count_vectorizer.fit_transform([review1, review2])
bag_of_words_sparse.todense(), count_vectorizer.get_feature_names()

C:\Users\chris\.virtualenvs\Maskininlarning-Christopher-Seander-nLYLwDGA\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


(matrix([[1, 1, 2, 0, 0, 1, 0],
         [0, 1, 0, 1, 1, 1, 1]], dtype=int64),
 ['about', 'book', 'love', 'no', 'okay', 'this', 'was'])

In [34]:
bag_of_words = pd.DataFrame(bag_of_words_sparse.todense(), columns=count_vectorizer.get_feature_names())

C:\Users\chris\.virtualenvs\Maskininlarning-Christopher-Seander-nLYLwDGA\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


## TF-IDF

In [41]:
tfidf_transformer = TfidfTransformer()
tfidf = tfidf_transformer.fit_transform(bag_of_words_sparse)
tfidf.todense()

matrix([[0.4078241 , 0.29017021, 0.81564821, 0.        , 0.        ,
         0.29017021, 0.        ],
        [0.        , 0.35520009, 0.        , 0.49922133, 0.49922133,
         0.35520009, 0.49922133]])

In [47]:
# creates tfidf vector in one go
tfidf_vectorizer = TfidfVectorizer()
tfidf_vectorizer.fit_transform([review1, review2]).todense()

matrix([[0.4078241 , 0.29017021, 0.81564821, 0.        , 0.        ,
         0.29017021, 0.        ],
        [0.        , 0.35520009, 0.        , 0.49922133, 0.49922133,
         0.35520009, 0.49922133]])

In [48]:
tfidf_vectorizer.get_feature_names()

C:\Users\chris\.virtualenvs\Maskininlarning-Christopher-Seander-nLYLwDGA\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['about', 'book', 'love', 'no', 'okay', 'this', 'was']